### ISSUE TITLE
ทำ Snapshot Testing

### ISSUE THREAD

**Issue by kajornsakp** [akexorcist/ruam-mij-android#16]

**Comment by kittinunf** [comment]
I can help work on this kub if everyone else is busy.

**Comment by akexorcist** [comment]
@

> I can help work on this kub if everyone else is busy.

@Judrummer

**Comment by Judrummer** [comment]
@kittinunf  oh thanks krub

**Comment by kittinunf** [comment]
@Judrummer Welcome as always kub ❤️ ^^ Please check my work here #47

**Comment by kittinunf** [comment]
https://github.com/akexorcist/ruam-mij-android/pull/51 Let's gooo kub
