### ISSUE TITLE
Mask warning/danger installed app as safe

### ISSUE THREAD

**Issue by akexorcist** [akexorcist/ruam-mij-android#27]
ในหน้า installed app ให้เพิ่มปุ่ม mark as safe สำหรับแอปที่มี installer เป็นเครื่องหมาย warning หรือ danger เพื่อให้ผู้ใช้กดยืนยันด้วยตัวเองว่าแอปนั้นปลอดภัยได้

เพราะมีบางแอปที่ติดมากับเครื่องแต่ว่ามี installer แปลก ๆ เช่น 
* installer เป็น `com.google.android.packageinstaller` แบบเดียวกับแอปที่ sideload 
* บางแอปมี installer เป็นตัวเอง เป็นต้น (มีผู้ใช้รายงานมา)

### To do
โดยเพิ่มปุ่มข้างล่างแต่ละ item แล้วย้ายปุ่มลูกศร > มาทำเป็นปุ่มอยู่ข้างๆแล้วเปลี่ยนเป็นคำว่า app info แทน

![Screenshot_20240322_011615_Ruam Mij~2](https://github.com/akexorcist/ruam-mij-android/assets/1949576/5064b131-f56b-4a97-a829-95b81641f851)

แอปไหนที่ยืนยันว่าปลอดภัย ให้เก็บแค่ package name ลง database ก็ได้ (จริงๆอยากให้เก็บพวก hash นะ แต่ถ้าแอปอัพเดทเวอร์ชันใหม่ hash ที่ว่าก็เปลี่ยนไปด้วย

### Wording
* ปุ่ม mark as safe
  * en : `Mark as safe`
  * th : `ยืนยันว่าปลอดภัย`
* ปุ่ม > ที่ย้ายมาอยู่ข้างล่างแทน
  * en : `App Info`
  * th : `ดูข้อมูล`

ที่ใช้คำแตกต่างกันเพราะเรื่องความยาวของคำ (พื้นที่วางปุ่มมีจำกัด และการสื่อความหมายต่อผู้ใช้ในภาษาไทยมากกว่า

### Note
* ต้องเพิ่ม Room Database เข้ามาในโปรเจคด้วย
* Task นี้ถือว่าเอาเรื่องอยู่นะ

**Comment by azygous13** [comment]
PR #34
