### ISSUE TITLE
Improve the contributors readme with `all-contributors` 

### ISSUE THREAD

**Issue by siriwatknp** [akexorcist/ruam-mij-android#31]
Hi, my name is Jun (the core team at [MUI](https://mui.com/)). As a Thai citizen, I really appreciate everyone's hard work on this project even though I am not familiar with android space. It's definitely making the society safer!.

One part that I see can be improved and help reduce chore tasks is using the [all-contributors](https://allcontributors.org/) bot to give 👏 to the contributors.

Here is what it looks like from one of my side project > https://github.com/siriwatknp/mui-treasury?tab=readme-ov-file#contributors-

Let me know if I can help with anything.

**Comment by akexorcist** [comment]
Thank you so much krubbbbb 🙏🙏
