### ISSUE TITLE
อยากให้ตั้งเวลาแสกนอัตโนมัติได้ และแจ้งเตือนเวลามีแอปไม่น่าไว้ใจตัวใหม่ขึ้นมาในระบบ

### ISSUE THREAD

**Issue by mix5003** [akexorcist/ruam-mij-android#36]

**Comment by akexorcist** [comment]
ตอนที่สร้างแอปนี้ขึ้นมา ตั้งใจว่าจะไม่มีการทำงานในเบื้องหลังครับ เพื่อลดการรบกวนผู้ใช้ให้น้อยที่สุดครับ

และการทำฟีเจอร์ดังกล่าวต้องประกาศ Permission เพิ่มอีก 2 ตัว ซึ่งจะขัดกับแอปที่ต้องการใช้ Permission ให้น้อยที่สุดเท่าที่จำเป็นต้องใช้จริง ๆ ครับ 

ดังนั้นต้องขอโทษด้วยครับ

**Comment by mix5003** [comment]
พอดีเห็น #17 เข้า roadmap เลยคิดว่าน่าจะต้องทำงานเบื้องหลังอยู่แล้ว อันนี้แค่เพิ่ม permission notification น่ะครับ 

ตัว usecase ผมคือ จะเอาไปลงให้ผู้ปกครอง แล้วให้มันทำงานอัตโนมัติ แล้วพอมันขึ้นแจ้งเตือนให้เค้ามาแจ้งเราอีกทีอ่ะครับ 

เลยฝากไว้ให้พิจารณา

**Comment by akexorcist** [comment]
#17 ไม่ได้ทำงานเบื้องหลังครับ เฉพาะตอนเปิดแอปเท่านั้นครับ ต้องทำแบบนั้นแทนเพื่อไม่ต้องเพิ่ม permission เช่นกันครับ

use case ที่ว่ามาผมก็เข้าใจดีว่ามันสะดวกกับผู้ใช้ แต่มันเป็น good to have feature ที่ต้องแลกมากับ permission ที่ต้งขอเพิ่มนี่แหละครับ ติดแค่เรื่องนี้เลย 

แต่ถ้าเป็นไอเดียอื่นที่ไม่ต้องขอ permission ก็เสนอเพิ่มเติมได้ครับผม
