### ISSUE TITLE
กดดูข้อมูลเพิ่มเติมของแอปได้

### ISSUE THREAD

**Issue by akexorcist** [akexorcist/ruam-mij-android#55]
เมื่อกดที่แอปใด ๆ ในหน้า Installed App ให้แสดง Bottom Sheet ขึ้นมาเพื่อแสดงข้อมูลของแอปนั้น

* ข้อมูลพื้นฐาน
  * Package name
  * App version
  * Installer
  * วันที่ติดตั้งแอปนี้
* `<uses-permission>` ที่ประกาศ
* Foreground service ที่มี
* ฯลฯ (ยังนึกไม่ออก)

**Comment by ultimagz** [comment]
ขอลองเอาไปทำครับ
มีคำถามตรง Foreground service นี่เอามายังไงเหรอครับ? ผมหาข้อมูลไม่เจอ
แล้ว UI นี่ทำมาเลยใช่มั้ยครับ?

**Comment by akexorcist** [comment]
@ultimagz foreground service ตอนแรกผมคิดไว้แค่ว่าดึง service ที่มีในแอปเพื่อหาอันที่ประกาศ serviceType แล้วมองว่าเป็น foreground service ก็ได้ แต่วิธีนี้จะใช้ได้เฉพาะแอปที่มาจาก google play เท่านั้น (เพราะ google play บังคับให้ประกาศ)

ผมเลยคิดว่าน่าจะตัดออกไปได้เลยครับ ส่วนเรื่อง UI เดี๋ยวผมช่วยทำให้ครับ รอก่อนนะครับ

**Comment by ultimagz** [comment]
@akexorcist อันนี้ UI ที่ผมลองทำไว้
![AppInfoBottomSheet](https://github.com/user-attachments/assets/038eea9b-03a1-4590-b4b2-731a0102a72d)

**Comment by akexorcist** [comment]
@ultimagz งั้นเดียวปรับ UI จากอันนี้เอาก็ได้ครับ จะได้ไม่ต้องทำอะไรเยอะ

**Comment by akexorcist** [comment]
@ultimagz ขอโทษด้วยครับที่ทำให้ช้า แต่[อิงตาม Figma](https://www.figma.com/design/0tgWegaUW7tMqjYLFhYIzL/Ruam-Mij-Design?node-id=0-1&t=J7J4o3ugZtsUwWr5-1) นี้ได้เลยครับ 

![image](https://github.com/user-attachments/assets/4d03a536-284a-40e4-af05-028d8a8db981)

รายละเอียดเพิ่มเติม

* Reuse component ที่มีอยู่แล้วมาใช้ได้เลย ถ้าอันไหนเป็น private function ก็ย้ายออกมาเป็นคลาสแยกใน package ที่ชื่อ component ได้เลย
* ขนาดและสีให้ดูจากชื่อ Layer
* คำอธิบายของ permission แต่ละตัวเดี๋ยวผมทำ mapper ให้เองครับ เบื้องต้นใช้เป็น empty string ไปก่อนได้เลย
* ในเมื่อเรากดเพื่อดูข้อมูลแบบ bottom sheet ได้เลย อยากให้เอาปุ่ม Mark as safe และ App info ในหน้า Installed App ออกไปเลยครับ แล้วเปลี่ยนมาแสดงในหน้าที่เราทำเพิ่มแทน
* พวกจุดเล็ก ๆ น้อย ๆ ที่ผมไม่ได้พูดถึง เอาตามที่เราคิดก่อนได้เลย เดี๋ยวผมมาปรับให้ทีหลังครับ

**Comment by ultimagz** [comment]
@akexorcist จากที่ลองปรับ ผมติดปัญหาเรื่องทำให้ส่วนของปุ่มด้านล่างสุด ณ BottomSheet state เป็น PartiallyExpanded ให้แสดงผลแบบ design ไมได้

**Comment by akexorcist** [comment]
@ultimagz เอาที่ใกล้เคียงเท่าที่ทำได้ก็ได้ครับ 5555
