### ISSUE TITLE
Publish app on F-Droid

### ISSUE THREAD

**Issue by akexorcist** [akexorcist/ruam-mij-android#78]
https://f-droid.org

**Comment by akexorcist** [comment]
Open merge request on F-Droid. See https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15725

**Comment by IzzySoft** [comment]
F-Droid's scanner seems to have missed a suspicious component in the app:

```
Offending libs:
---------------
* Google Mobile Services (/com/google/android/gms): NonFreeComp

1 offenders.
```

And another suspicious blob:

```
SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

(if you forgive me the pun on the irony: did the app check itself at least once? :speak_no_evil: :dash:)

OK, let's stay constructive. GMS was dragged in by this:

```kotlin
implementation(libs.play.oss.licenses)
```

Known culprit. [See here](https://gitlab.com/-/snippets/1896503#license-dialogs) for a short explanation and possible alternatives.

`DEPENDENCY_INFO_BLOCK` can easily be avoided with a small addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

If you let me know once the two are fixed and the corresponding release is available, I could check again – and probably add your app to the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid) if you want me to. But without that being fixed, F-Droid will reject inclusion (and they should find out when they build the app, which didn't yet happen…

**Comment by akexorcist** [comment]
Now available on F-Droid

https://f-droid.org/en/packages/com.akexorcist.ruammij/
